version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: church-planner-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - church-planner-network

  # MongoDB Express Web UI (optional but helpful for development)
  mongo-express:
    image: mongo-express:latest
    container_name: church-planner-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - church-planner-network

networks:
  church-planner-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 