global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "server"
    static_configs:
      - targets: ["server:8080"]
    metrics_path: "/metrics"

  - job_name: "client"
    static_configs:
      - targets: ["client:3000"]
    metrics_path: "/metrics"

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb:27017"]
    metrics_path: "/metrics"

  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9323"] 