name: Church Planner CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-client:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'client/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./client
      run: npm ci
    
    - name: Lint
      working-directory: ./client
      run: npm run lint
    
    - name: Type check
      working-directory: ./client
      run: npm run type-check
    
    - name: Test
      working-directory: ./client
      run: npm test
  
  test-server:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: [6.0]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'server/package-lock.json'
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    
    - name: Install dependencies
      working-directory: ./server
      run: npm ci
    
    - name: Lint
      working-directory: ./server
      run: npm run lint
    
    - name: Type check
      working-directory: ./server
      run: npm run type-check
    
    - name: Test
      working-directory: ./server
      run: npm test
      env:
        MONGO_URI: mongodb://localhost:27017/church_planner_test
        JWT_SECRET: test_secret_for_ci
        NODE_ENV: test
  
  build:
    needs: [test-client, test-server]
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Build client
      working-directory: ./client
      run: |
        npm ci
        npm run build
    
    - name: Build server
      working-directory: ./server
      run: |
        npm ci
        npm run build 